### ISSUE TITLE
--between_sample_distances is giving empty outputs

### ISSUE THREAD

**Issue by hannahaichelman** [didillysquat/SymPortal_framework#42]
When I try to look at between sample distances, not getting any files output into the output/ordination/ folder

**Comment by didillysquat** [comment]
Hi Hannah!

Thanks for taking the time to raise this issue. 

This problem was caused due to the distance calculation class in question being instantiated but not actually run in the code. It was a bug in the v0.3.0. release.

It is now fixed as of the [v0.3.5 release](https://github.com/didillysquat/SymPortal_framework/releases/tag/v0.3.5).
