### ISSUE TITLE
Use file paths from sheet file

### ISSUE THREAD

**Issue by timkahlke** [didillysquat/SymPortal_framework#85]
Hi,

It would be great if SP could use the paths supplied in the sheet file instead of needing the "--load" path. That way files from different projects/locations could be loaded without the need to copy them all into one directory.

Thanks for SP btw :),
Tim

**Comment by didillysquat** [comment]
Starting work on this now. 

We will implement it so that a path to a directory will still be provided to the "--load" argument. 
This directory will be used for the temp and intermediate files.

However, when a datasheet is provided, if a path is provided for the fwd and rev reads, then SP will look for the sequencing file at this location rather than in the directory provided as an argument to the --load function. Else, if only a file name is given, the file will be looked for in the directory provided to --load.

**Comment by didillysquat** [comment]
Documentation updated: https://github.com/didillysquat/SymPortal_framework/wiki/Running-SymPortal#loading-samples-from-multiple-directories
